In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



## Part 1: Theoretical Queltionk
## 1.What are the different data structures used in Tensorflow?. Give some examplesc

## Tensors: The fundamental data structure in TensorFlow is the tensor, a multidimensional array capable of storing various data types, including integers, floats, strings, and booleans. Tensors represent data flowing through the computational graph, forming the backbone of TensorFlow operations. 
## Example:  A rank-2 tensor representing a 2D image could have dimensions [height, width], where each element corresponds to a pixel intensity value.

## Ragged Tensors: Ragged tensors are an extension of traditional tensors designed to handle data with varying lengths along one or more dimensions. They efficiently represent sequences of different lengths, such as text sentences or time series data.
## Example: A ragged tensor could represent a batch of text sentences, where each element is a variable-length array of words.

## Sparse Tensors: Sparse tensors are optimized for storing data with a large proportion of zero values. They represent only the non-zero elements, significantly reducing memory usage and improving computational efficiency for sparse data.
## Example: A sparse tensor could represent a user-item interaction matrix, where most entries are zeros indicating no interaction, and only the non-zero elements represent interactions.

## 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

## TensorFlow Constants:
## Constants are created using tf.constant().
## Constants have fixed values that cannot be changed after initialization

## TensorFlow Variables:
## Variables are created using tf.Variable() and require an initial value.
## Variables can be modified during the execution of a TensorFlow program using methods like assign.

## 3.Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

## Matrix Addition: Matrix addition in TensorFlow is performed using the tf.add() function. This function takes two tensors of the same shape and adds their corresponding elements. The resulting tensor will have the same shape as the input tensors.

## Multiplication: Matrix multiplication in TensorFlow is performed using the tf.matmul() function. It takes two matrices as input and returns their product. The matrices must have compatible dimensions for multiplication to be valid. The first matrix must have dimensions (m x n) and the second matrix must have dimensions (n x p) to produce a resulting matrix with dimensions (m x p).

## Element-wise Operations: Element-wise operations in TensorFlow are performed using functions like tf.multiply(), tf.add(), tf.subtract(), and tf.divide(). These functions take two tensors as input and perform the corresponding element-wise operation on them. The tensors must have the same shape for the operation to be valid. If the shapes are not compatible, TensorFlow will automatically broadcast the smaller tensor to match the larger one.

##  Part2: Practical Implementation.
## Talk 1: Creating and Manipulating Matrices
## 1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A

In [44]:
import tensorflow as tf
import warnings

A = tf.random.normal(shape=(2,2), mean=0, stddev=1.0)
A

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.04542409, -1.1554974 ],
       [ 0.6262364 ,  1.4490418 ]], dtype=float32)>

## 2.Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix B

In [45]:
x = 2
# Create a Gaussian matrix B with dimensions x
B = tf.random.truncated_normal(shape=(x, x), mean=0, stddev=1.0, dtype=tf.float32)
B

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.4912187 , -0.70473677],
       [ 0.6188489 , -0.871338  ]], dtype=float32)>

## 3.Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values of matrix c

In [46]:
C = tf.random.normal(shape =(2,2) , mean=2 , stddev=0.2)
C

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.3268077, 1.9364322],
       [1.9602354, 1.8697691]], dtype=float32)>

## 4.Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [47]:
# Perform matrix addition between A and B
A = tf.random.normal(shape=(2,2), mean=0, stddev=1.0)

B = tf.random.truncated_normal(shape=(2, 2), mean=0, stddev=1.0, dtype=tf.float32)

D = A+B
D

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.5350866 ,  0.34832734],
       [ 0.49547184,  1.206335  ]], dtype=float32)>

## 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [48]:
# Perform matrix multiplication between C and D
E = tf.matmul(C, D)
E

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.285596  ,  3.1464767 ],
       [-0.12247765,  2.9383714 ]], dtype=float32)>

## Talk 2: Per;orming Additional Matrix Operationk
## 1.Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform functionc

In [39]:
# Create a 2x2 matrix of random uniform values between 0 and 10
F = tf.random.uniform(shape=(2,2), minval=0, maxval=10)
F

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[9.395036, 5.947405],
       [8.516697, 0.815568]], dtype=float32)>

## 2.Calculate the transpose of matrix F and store the result in matrix G.

In [40]:
# Calculate the transpose of matrix F
G = tf.transpose(F)
G

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[9.395036, 8.516697],
       [5.947405, 0.815568]], dtype=float32)>

## 3.Calculate the elementDwise exponential of matrix F and store the result in matrix H.

In [41]:
# calculate the ElementDwise Exponential of maxtrix F
H = tf.exp(F)
H

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.2028520e+04, 3.8275873e+02],
       [4.9975195e+03, 2.2604592e+00]], dtype=float32)>

## 4.Create a matrix I by concatenating matrix F and matrix G horizontally.

In [42]:
# Concatenate matrix F and matrix G horizontally
I = tf.concat([F, G], axis=1)
I

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[9.395036, 5.947405, 9.395036, 8.516697],
       [8.516697, 0.815568, 5.947405, 0.815568]], dtype=float32)>

## 5.Create a matrix J by concatenating matrix F and matrix H vertically.

In [43]:
# Concatenate matrix F and matrix H vertically
J = tf.concat([F, H], axis=0)
J

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[9.3950357e+00, 5.9474049e+00],
       [8.5166969e+00, 8.1556797e-01],
       [1.2028520e+04, 3.8275873e+02],
       [4.9975195e+03, 2.2604592e+00]], dtype=float32)>